# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FeaturesProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FeaturesProject

  pod 'Reusable'
  pod 'Cartography'

  target 'FeaturesProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FeaturesProjectUITests' do
    # Pods for testing
  end

end
